### ISSUE TITLE
Lealflet inside Angular Material Tab doesn't work

### ISSUE THREAD

**Issue by ericpatrick** [bluehalo/ngx-leaflet#223]
Hello,
I'm trying to render a leaflet map inside a tab component of Angular Material, but the map doesn't show the layer or just show some tiles. When I put the map div outside of tab, the map show layer normally. I looked for a console error message but didn't show anything. Can anyone tell me what's going on, please?

## Versions

Angular: 7.2.15
Angular-material: 7.3.7
Ngx-leaflet: 5.0.2
Leaflet: 1.5.1

## Example on stackblitz

https://stackblitz.com/edit/angular-b8nnsg

**Comment by LucasFrecia** [comment]
Forcing map to re render should fix that. Had same problem in one proyect using onPush change detection.

```html
          <div leaflet (leafletMapReady)="onMapReady($event)">
          </div>  
```

```ts
  onMapReady(map: Map): void {
    setTimeout(() => {
      map.invalidateSize();
    });
  }
```

**Comment by maxweigand** [comment]
Just change the url from:
``` http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png ```
to
```https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png```

**Comment by ericpatrick** [comment]
@maxweigand , this change don't solve the problem.
Someone called Lucas Frecia post a message that fix the problem. I don't know why his answer didn't show here, but I'll explain. He said the leaflet have some problem with onPush change detection. To solve it, it's necessary re render the map `invalidateSize()`. Something like this:

**app.component.html**
```javascript
<div leaflet (leafletMapReady)="onMapReady($event)">
</div>
```

**app.component.ts**
```javascript
onMapReady(map: Map): void {
    setTimeout(() => {
      map.invalidateSize();
    });
}
```
Thanks Lucas.

But I didn't understand why it happen with leaflet in this case. Is it a bug or is it a expected behavior?

**Comment by maxweigand** [comment]
I can't reproduce your described behaviour. 
As soon as I open your stackblitz link, everything is working as expected.
The contributers might have a look at this ;)

**Comment by ericpatrick** [comment]
So sorry Max, probably when you open I was testing another solutions. The problem remains the same as I described above. The picture below shows what happen in my project:

![Captura de tela de 2019-05-27 10:40:23](https://user-images.githubusercontent.com/5290097/58424366-a6382a00-806d-11e9-9c47-a14362ed8851.png)

If you uncomment the code inside the `onMapReady` function (that I added after), the problem will be fixed :)

**Comment by reblace** [comment]
**What's the issue?**
Leaflet uses the size of the map container to determines its grid layout for the map tiles. When the map container changes size, Leaflet has to recaculate its layout. You can force this to happen by calling `map.invalidateSize().`

**How does ngx-leaflet handle this?**
The `ngx-leaflet plugin` registers a callback on window resize events. The callback function calls `map.invalidateSize()` for you so you don't have to worry about it (most of the time).

**Why is it breaking in this case?**
Angular Material (and Bootstrap) accordions, panels, tabs, etc. use Javascript to show/hide/resize elements on the page that change the size of the map container. In these situations, neither ngx-leaflet nor Leaflet have any way of knowing what has happened. As a result, you have to call `map.invalidateSize()` yourself.

Your solution of adding the call to `map.invalidateSize()` is partially correct. It will probably fix it for the initial render of the map. But, you're still going to need to call `map.invalidateSize()` when you change tabs away from the map, change the size of the window, and then change tabs back to the map.

I'd recommend you register a callback on the equivalent of a "tab shown/changed/clicked" event and add a call to `map.invalidateSize()`. You can get a reference to the map using the ngx-leaflet plugin `(leafletMapReady)` event emitter. That should make sure that any time the tabs are changed, the map will be redrawn correctly.

**Comment by hoangngk** [comment]
Hi @ericpatrick , @reblace 
I have the same problem and I tried to follow the way you did. But the problem hasn't still been gone. Could you please take a look at the attachement 

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/11712906/61102850-d7dc4780-a499-11e9-801a-fce4e35376cb.png">

it seems whether I am having two maps on the same time or the map is shown on popup ?

**Comment by hoangngk** [comment]
I found the problem, please ignore it, thanks

**Comment by deadmann** [comment]
so i also need to anchor an event to windows resizing too...
how can i subscribe to windows resizing?

**Comment by reblace** [comment]
@deadmann https://stackoverflow.com/questions/35527456/angular-window-resize-event

Closing this since the original question has been answered.

**Comment by bekzodrozmetov** [comment]
muttahamlar )

**Comment by acharyaronak** [comment]
Lealflet inside Angular Material Tab doesn't work issue has been fixed when i intialize map on tab change.
onTabChange(event: MatTabChangeEvent) {
  if (event.index === <your_map_tab_index>) {
    this.mapTabActive = true;
    this.initializeMap();
  } else {
    this.mapTabActive = false;
  }
} 
<div *ngIf="mapTabActive">
    <div id="leaflet-map" style="height: 400px;"></div>
  </div>
